import {
  FaFistRaised,
  FaRunning,
  FaLaughSquint,
  FaTheaterMasks,
  FaHeart,
  FaRobot,
  FaMusic,
  FaSkull,
  FaGhost,
} from "react-icons/fa";
import {
  GiFairyWand,
  GiFairyWings,
  GiLoveMystery,
  GiSpaceShuttle,
  GiTimeTrap,
  GiPerspectiveDiceSixFacesRandom,
  GiDualityMask,
} from "react-icons/gi";
import { MdSportsEsports, MdSelfImprovement } from "react-icons/md";
import { RiMentalHealthFill } from "react-icons/ri";

export const animeGenres = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Hentai",
  "Horror",
  "Mahou Shoujo",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
];

export const genreIcons = {
  Action: FaFistRaised,
  Adventure: FaRunning,
  Comedy: FaLaughSquint,
  Drama: FaTheaterMasks,
  Ecchi: GiPerspectiveDiceSixFacesRandom,
  Fantasy: GiFairyWings,
  Hentai: GiDualityMask,
  Horror: FaSkull,
  "Mahou Shoujo": GiFairyWand,
  Mecha: FaRobot,
  Music: FaMusic,
  Mystery: GiLoveMystery,
  Psychological: RiMentalHealthFill,
  Romance: FaHeart,
  "Sci-Fi": GiSpaceShuttle,
  "Slice of Life": MdSelfImprovement,
  Sports: MdSportsEsports,
  Supernatural: FaGhost,
  Thriller: GiTimeTrap,
};

export const genreColors = {
  Action: { bg: "#ff4c4c", text: "#fff", shadow: "#cc0000" },
  Adventure: { bg: "#ff914d", text: "#fff", shadow: "#cc5c00" },
  Comedy: { bg: "#ffd93d", text: "#000", shadow: "#e0b800" },
  Drama: { bg: "#a471ff", text: "#fff", shadow: "#7741cc" },
  Ecchi: { bg: "#ff69b4", text: "#fff", shadow: "#d61a92" },
  Fantasy: { bg: "#6ecbff", text: "#000", shadow: "#2ca4d8" },
  Hentai: { bg: "#e60073", text: "#fff", shadow: "#99004d" },
  Horror: { bg: "#2b2d42", text: "#fff", shadow: "#1a1b28" },
  "Mahou Shoujo": { bg: "#ffb6f2", text: "#000", shadow: "#ff70d2" },
  Mecha: { bg: "#8d99ae", text: "#fff", shadow: "#5c677d" },
  Music: { bg: "#70e000", text: "#000", shadow: "#4bae00" },
  Mystery: { bg: "#3a0ca3", text: "#fff", shadow: "#240070" },
  Psychological: { bg: "#7209b7", text: "#fff", shadow: "#48007a" },
  Romance: { bg: "#ff6b81", text: "#fff", shadow: "#cc3a50" },
  "Sci-Fi": { bg: "#00b4d8", text: "#fff", shadow: "#007ca1" },
  "Slice of Life": { bg: "#f9c74f", text: "#000", shadow: "#c49b00" },
  Sports: { bg: "#00bbf9", text: "#000", shadow: "#0091c2" },
  Supernatural: { bg: "#6a4c93", text: "#fff", shadow: "#43296a" },
  Thriller: { bg: "#d00000", text: "#fff", shadow: "#900000" },
};
